# canary-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      run: canary
  replicas: 2
  template:
    metadata:
      labels:
        run: canary
    spec:
      containers:
      - name: canary
        image: us-central1-docker.pkg.dev/kubernetes-cc-2025-478900/ml-models/canary:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: gcp-artifact-registry