# elector-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elector
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      run: elector
  replicas: 2
  template:
    metadata:
      labels:
        run: elector
    spec:
      containers:
      - name: elector
        image: us-central1-docker.pkg.dev/kubernetes-cc-2025-478900/ml-models/elector:latest
        ports:
        - containerPort: 5002
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: gcp-artifact-registry